export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as Login } from './Login'
export { default as Home } from './Home'
export { default as HomeML } from './HomeML'
export { default as HomePUBG } from './HomePUBG'
export { default as HomeValo } from './HomeValo'
export { default as SignUp} from './SignUp'
